### ISSUE TITLE
use for YOLO

### ISSUE THREAD

**Issue by bobo12138** [yihui-he/softer-NMS#10]
HELLO, I want to add softer-NMS in YOLO-NMS , what should I do to change the code ?  thanks.

**Comment by yihui-he** [comment]
@bobo12138 have a look at YOLOv3 + KL-loss https://github.com/yihui-he/KL-Loss#pytorch-re-implementations
BTW, this repo is deprecated. Please use our new repo: https://github.com/yihui-he/KL-Loss
