### ISSUE TITLE
when train on our own dataset, error occurs,

### ISSUE THREAD

**Issue by chanajianyu** [yihui-he/softer-NMS#11]
json_stats: {"accuracy_cls": 0.944484, "bbox_pred_std_abs_logw_loss": NaN, "bbox_pred_std_abs_mulw_loss": NaN, "eta": "9:15:45", "iter": 2740, "loss": NaN, "loss_bbox": NaN, "loss_cls": NaN, "loss_rpn_bbox_fpn2": NaN, "loss_rpn_bbox_fpn3": NaN, "loss_rpn_bbox_fpn4": NaN, "loss_rpn_bbox_fpn5": 0.000000, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": NaN, "loss_rpn_cls_fpn3": NaN, "loss_rpn_cls_fpn4": NaN, "loss_rpn_cls_fpn5": 0.004753, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.002500, "mb_qsize": 64, "mem": 7410, "time": 0.382141}
CRITICAL train.py:  98: Loss is NaN

**Comment by chanajianyu** [comment]
the yaml file is like this:


MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
NUM_GPUS: 2
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  MAX_ITER: 90000
  STEPS: [0, 60000, 80000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: /app/hd4t/jingwei.wang/opt/app/rcnn/softer-NMS/softer-nms/R-50.pkl
  DATASETS: ('head_train', )
  SCALES: (800,)
  MAX_SIZE: 1333
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  DATASETS: ('coco_2018_test',)
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  SOFT_NMS:
    ENABLED: True
    METHOD: gaussian
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: .
XYXY: True
PRED_STD: True
STD_NMS: True

**Comment by yihui-he** [comment]
Seems weird. It works fine on COCO and PASCAL VOC.
BTW, this is a pre-print version of our paper and the training is very unstable. After the release of final decision to conference submission, we'll update the most recent version which only requires single stage of training and also improves the AP to 38.0% (previously 37.8%).
Stay tuned

**Comment by yihui-he** [comment]
please refer to our CVPR'19 code: https://github.com/yihui-he/KL-Loss
