### ISSUE TITLE
Detectron module

### ISSUE THREAD

**Issue by Francis0625** [yihui-he/softer-NMS#13]
Your project is adapted based on the origin FAIR Detectron, so I directly "make" in the folder. After $make, it said "Installed /media/hh/D/softer-NMS-master
Processing dependencies for Detectron==0.0.0
Finished processing dependencies for Detectron==0.0.0".
But when I do the test "python detectron/tests/test_spatial_narrow_as_op.py",thesr is a error "File "detectron/tests/test_spatial_narrow_as_op.py", line 88, in <module>
    c2_utils.import_detectron_ops()
  File "/media/XX/D/softer-NMS-master/detectron/utils/c2.py", line 43, in import_detectron_ops
    detectron_ops_lib = envu.get_detectron_ops_lib()
  File "/media/XX/D/softer-NMS-master/detectron/utils/env.py", line 72, in get_detectron_ops_lib
    ('Detectron ops lib not found; make sure that your Caffe2 '
AssertionError: Detectron ops lib not found; make sure that your Caffe2 version includes Detectron module". I tried many times, but still can not solve this problem.Is it necessary to download the source code of Detecton?

**Comment by yihui-he** [comment]
It suggests that it can't find Detectron ops lib in your caffe2

**Comment by Francis0625** [comment]
Thanks a lot.  The problem fixed. But i meet another problem.
When testing, there is an error.
Code:
python2 tools/test_net.py \
    --cfg configs/12_2017_baselines/fast_rcnn_R-50-FPN_2x_our.yaml \
    --multi-gpu-testing \
    NUM_GPUS 1

error:
INFO test_net.py:  98: Called with args:
INFO test_net.py:  99: Namespace(cfg_file='configs/12_2017_baselines/fast_rcnn_R-50-FPN_2x_our.yaml', multi_gpu_testing=True, opts=['NUM_GPUS', '1'], range=None, vis=False, wait=True)
Traceback (most recent call last):
  File "/media/XX/D/softer-NMS-master/tools/test_net.py", line 101, in <module>
    merge_cfg_from_file(args.cfg_file)
  File "/media/XX/D/softer-NMS-master/detectron/core/config.py", line 1140, in merge_cfg_from_file
    _merge_a_into_b(yaml_cfg, __C)
  File "/media/XX/D/softer-NMS-master/detectron/core/config.py", line 1200, in _merge_a_into_b
    _merge_a_into_b(v, b[k], stack=stack_push)
  File "/media/XX/D/softer-NMS-master/detectron/core/config.py", line 1190, in _merge_a_into_b
    raise KeyError('Non-existent config key: {}'.format(full_key))
KeyError: u'Non-existent config key: TEST.SOFT_NMS.ENABLED'

what is the reason for this?

**Comment by Francis0625** [comment]
> It suggests that it can't find Detectron ops lib in your caffe2

thanks a lot. The reason is the the source code Detectron has update, so some path need to modify of your project.
