### ISSUE TITLE
x1y1x2y2 Coordinates only in FasterRCNN head?

### ISSUE THREAD

**Issue by LandyGuo** [yihui-he/softer-NMS#14]
In softer-nms paper:
> simply training with x1, y1, x2, y2 coordinates instead of the standard x, y, w, h coordinates improves the AP by 0.7%

My question is: Are x1,y1,x2,y2 coordinates used only in FasterRCNN head or both FasterRCNN and RPN heads ?  The paper does not make it clear.
Hoping for your timely response:)

**Comment by yihui-he** [comment]
It's for both.
https://github.com/yihui-he/softer-NMS/blob/master/detectron/roi_data/rpn.py#L212-L214

https://github.com/yihui-he/softer-NMS/blob/master/detectron/roi_data/data_utils.py#L123
