### ISSUE TITLE
Can this method be used in one-stage detector like retinanet?

### ISSUE THREAD

**Issue by zoe218** [yihui-he/softer-NMS#18]
Dear author,
Have you tried softer-NMS in retinanet or other else one-stage detectors? 
Is this method also performs well in one-stage detectors?

**Comment by yihui-he** [comment]
@zoe218 Yes, have a look at YOLOv3 + KL-loss https://github.com/yihui-he/KL-Loss#pytorch-re-implementations
BTW, this repo is deprecated. Please use our new repo: https://github.com/yihui-he/KL-Loss
