### ISSUE TITLE
我在fine turn我之前训练的模型的时候，为什么bbox_pred_std_abs_logw_loss为负值？

### ISSUE THREAD

**Issue by gittigxuy** [yihui-he/softer-NMS#5]
我已经将三个都设置为true了

**Comment by yihui-he** [comment]
log的原因，这一项可以是负值

**Comment by emmra** [comment]
但是负值训练绝对loss数值越来越大，从"bbox_pred_std_abs_logw_loss": -0.083365。到。"bbox_pred_std_abs_logw_loss": -1.142597, 而且最后的mAP值降低了，前9万次只将XYXY项设为True时mAP为0.75。然后把所有增加项都设为True后又接着训练到18万次，mAP值却只有0.74？？？

**Comment by yihui-he** [comment]
this repo is deprecated. Please use our new repo which also improved performance: https://github.com/yihui-he/KL-Loss
