### ISSUE TITLE
Some question about "confs"

### ISSUE THREAD

**Issue by aimhabo** [yihui-he/softer-NMS#6]
### Expected results

What did you expect to see?
> what's std1 and std0 in py_cpu_nms.py？
> and how could I calculate it?

### Actual results

What did you observe instead?

> py_cpu_nms.py::[41-42]::
>             std1 = confidence[i, j]
>             stdo = confidence[:, j]

> test.py::[794-796]::
>             confs_j = confs[inds, j * 4:(j + 1) * 4]
>             nms_dets, _ = py_nms_utils.soft(dets_j,
>                     confidence=confs_j )

> test.py::[82]::
>             scores, boxes, cls_boxes = box_results_with_nms_and_limit(scores, boxes, confs=confs)

> test.py::[67]::
>             scores, boxes, im_scale, confs = im_detect_bbox(
>                 model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
>             )

> test.py::[176]::
>             confs = workspace.FetchBlob(core.ScopedName('bbox_pred_std_abs'))

what's "bbox_pred_std_abs" and what's the content of confs?

**Comment by yihui-he** [comment]
std1 and std0 are used for some other ideas. they are not used in softer-NMS.
bbox_pred_std_abs is BBOX PREDiction STandard Deviation ABSolute value  
confs are bbox boundary confidences

**Comment by aimhabo** [comment]
@yihui-he I get it, thank you

**Comment by yihui-he** [comment]
I just cleaned up the code. It's easier for reading now.
