### ISSUE TITLE
第二阶段训练后，mAP值降低了？？

### ISSUE THREAD

**Issue by DetectionIIT** [yihui-he/softer-NMS#9]
你好，看之前您有说道：”log的原因，这bbox_pred_std_abs_logw_loss一项可以是负值。“
但是负值训练这一项绝对loss数值越来越大，从"bbox_pred_std_abs_logw_loss": -0.083365到"bbox_pred_std_abs_logw_loss": -1.142597, 而且最后的mAP值降低了，前9万次只将XYXY项设为True时mAP为0.75。然后把所有增加项都设为True后又接着训练到18万次，mAP值却只有0.74？？？

谢谢！！

**Comment by yihui-he** [comment]
Thanks for your interest! I also noticed this problem. This is a pre-print version of our paper and the training is very unstable. 
After the release of final decision to conference submission, we'll update the most recent version which only requires single stage of training and also improves the AP to 38.0% (previously 37.8%).
Stay tuned

**Comment by yihui-he** [comment]
please refer to our CVPR'19 code: https://github.com/yihui-he/KL-Loss

**Comment by DetectionIIT** [comment]
Thanks.


| |
郭伟
邮箱：guowei3158@126.com
|

签名由 网易邮箱大师 定制

在2019年04月23日 03:02，Yihui He 何宜晖 写道：

Closed #9.
